services:
    vinfrag.hide.listener:
        class: vinfrag\hide\event\listener
        arguments:
            - '@vinfrag.hide.helper'
            - '@user'
            - '@request'
        tags:
            - { name: event.listener }

    vinfrag.hide.helper:
        class: vinfrag\hide\includes\helper
        arguments:
            - '@dbal.conn'
            - '@filesystem'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
